In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sqlalchemy import create_engine
from ast import literal_eval
import json

%matplotlib inline

In [2]:
# Postgres username, password, and database name
POSTGRES_ADDRESS = 'localhost'

POSTGRES_PORT = '5432'
POSTGRES_USERNAME = 'vegas'
POSTGRES_PASSWORD = 'VrichCrich99'
POSTGRES_DBNAME = 'univers'

In [3]:
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'.format(username=POSTGRES_USERNAME, password=POSTGRES_PASSWORD, ipaddress=POSTGRES_ADDRESS, port=POSTGRES_PORT, dbname=POSTGRES_DBNAME))
cnx = create_engine(postgres_str)

In [4]:
appstech_labs_id = 1
df = pd.read_sql_query(f"SELECT discount_rate, discount_amount, sales_tax_rate, sales_tax_amount, exchange_rate, gross_cost, margin, gross_amount, txn_date FROM user_sales_table where appstech_labs_id='{appstech_labs_id}'", cnx, index_col='txn_date', parse_dates=['txn_date'])
df.head()

,discount_rate,discount_amount,sales_tax_rate,sales_tax_amount,exchange_rate,gross_cost,margin,gross_amount
txn_date,,,,,,,,
2020-07-26,0.0,0.00,0.0,0.00,1.0,0.0,140.00,140.00
2020-07-28,10.0,8.75,0.0,0.00,1.0,0.0,78.75,78.75
2020-07-05,0.0,0.00,0.0,0.00,1.0,0.0,225.00,225.00
2020-07-30,0.0,0.00,8.0,26.82,1.0,135.0,200.25,335.25
2020-07-30,0.0,0.00,0.0,0.00,1.0,167.5,310.00,477.50